[stack]
name = "base"
extends = ""
runtime = "bun"
scaffold = ""

[sync]
source = "configs"

[dependencies.dev]
packages = [
    "prettier",
    "cspell",
    "husky",
    "@commitlint/cli",
    "@commitlint/config-conventional",
]

[scripts]
"check:spell" = "cspell '**' --no-progress --color --show-context"
"check:format" = "prettier --check --ignore-path .gitignore . && shfmt --diff --indent 2 **/*.sh"
"check:shell" = "shellcheck --severity=warning **/*.sh"
"format" = "prettier --write --ignore-path .gitignore . && shfmt --write --indent 2 **/*.sh"
"prepare" = "husky"
"check" = "./scripts/verify.sh"
"clean" = "./scripts/clean.sh"
"update" = "./scripts/update.sh"
